### PR TITLE
Introduce `#[napi]` procedural macro to automation development boilerplate

### PR DESCRIPTION
**Pull request by forehalo**
See the discussion: #684. This PR would include all the things listed below

- [x] implements the macro: `#[napi]`
  - [x] function
  - [x] js <=> rust value mapping
    - [x] boolean/numbers
    - [x] strings
    - [x] T | undefined <=> Option 
    - [x] Class <=> Struct
    - [x] literal object
    - [x] Array <=> Vec<_>
    - [x] enum
    - [x] callback
    - [x] buffer
    
  - [x] auto-exports
    - [x] functions
    - [x] structs
    - [x] impls
    - [x] enum
 - [x] runtime arguments validation
    - [x] arguments length
    - [x] arguments type(`#[napi(strict)]`, would be slow) 
 - [x] typescript type generation
 - [x] testing

What would come with releases later on:

- typed array
- async functions
- auto serde serialization/deserialization

Greatly thank [wasm_bindgen](https://github.com/rustwasm/wasm-bindgen) for where the idea originally coming from when exploring it's codebase, and [node_bindgen](https://github.com/infinyon/node-bindgen) for the idea of implicit exports registering at runtime.

### CODE REVIEW

**Comment by forehalo** [comment]
good start

image

**Comment by jaredpalmer** [comment]
Just want to say that this PR is awesome. This will dramatically lower the barrier to entry for JS devs just learning Rust while also removing boilerplate. 

+1000000000000 for this

**Comment by numToStr** [comment]
This is beautiful ♥️. I thought of using `napi_rs` before but It was too verbose but now it is soo much clean and simple. I am going to play with this PR on my project https://github.com/numtostr/zenv

**Comment by Brooooooklyn** [comment]
|                          | napi-rs                    | napi-rs-compat                | neon                        | node-bindgen                |
| ------------------------ | -------------------------- | ----------------------------- | --------------------------- | --------------------------- |
| Sum (a + b)              | 36 121 906 ops/s  **100%** | 36 021 114 ops/s   **99.72%** | 9 438 807 ops/s  **26.13%** | 7 522 062 ops/s  **20.82%** |
| Concat(Hello + " world") | 4 526 668 ops/s **100%**   | 4 336 416 ops/s  **95.95%**   | 3 973 988 ops/s  **85.09%** | 2 747 707 ops/s  **60.93%** |

**Review by Brooooooklyn — APPROVED** [review]

**Pull request merged**
