### PR TITLE
feat(napi): support `Return` generic of ThreadsafeFunction

### PR DESCRIPTION
**Pull request by Brooooooklyn**
- [x] Migrate internal API away from `JsFunction`
- [ ] Write migration guide

### `ThreadsafeFunction` can be function arguments

```rust
#[napi]
pub fn accept_threadsafe_function_tuple_args(func: ThreadsafeFunction<(u32, bool, String)>) {
  thread::spawn(move || {
    func.call(
      Ok((1, false, "NAPI-RS".into())),
      ThreadsafeFunctionCallMode::NonBlocking,
    );
  });
}
```

⬇️⬇️⬇️

```ts
export function acceptThreadsafeFunctionTupleArgs(func: (err: Error | null, arg0: number, arg1: boolean, arg2: string) => any): void
```

### `ThreadsafeFunction` can define `Return` generic

```rust
#[napi]
pub fn accept_threadsafe_function_tuple_args(func: ThreadsafeFunction<(u32, bool, String), String>) {
  thread::spawn(move || {
    func.call(
      Ok((1, false, "NAPI-RS".into())),
      ThreadsafeFunctionCallMode::NonBlocking,
    );
  });
}
```

⬇️⬇️⬇️

```ts
export function acceptThreadsafeFunctionTupleArgs(func: (err: Error | null, arg0: number, arg1: boolean, arg2: string) => string): void
```

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
* **#1997** <a href="https://app.graphite.dev/github/pr/napi-rs/napi-rs/1997?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Brooooooklyn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Boshen** [comment]
We've locked our version to another branch for now

https://github.com/web-infra-dev/rspack/blob/006f685800f5a00d55cd1b5129999eee83af63f5/Cargo.toml#L57-L60

```
napi              = { git = "https://github.com/h-a-n-a/napi-rs", branch = "rspack" }
napi-build        = { git = "https://github.com/h-a-n-a/napi-rs", branch = "rspack" }
napi-derive       = { git = "https://github.com/h-a-n-a/napi-rs", branch = "rspack" }
napi-sys          = { git = "https://github.com/h-a-n-a/napi-rs", branch = "rspack" }
```

**Comment by Brooooooklyn** [comment]
I'll cherry-pick his changes into this branch and publish an alpha version based on this

**Comment by Brooooooklyn** [comment]
@h-a-n-a In this implementation, the `CalleeHandled` ThreadsafeFunction should receive `Result<Return>` in the callback rather than `Return`:

```rust
#[napi]
pub fn tsfn_call_with_callback(tsfn: ThreadsafeFunction<(), String>) -> napi::Result<()> {
  tsfn.call_with_return_value(
    Ok(()),
    ThreadsafeFunctionCallMode::NonBlocking,
    |value: Result<String>| {
      let value = value.expect("Failed to retrieve value from JS");
      println!("{}", value);
      assert_eq!(value, "ReturnFromJavaScriptRawCallback".to_owned());
      Ok(())
    },
  );
  Ok(())
}
```

Is this what you want?

**Comment by h-a-n-a** [comment]
> @h-a-n-a In this implementation, the `CalleeHandled` ThreadsafeFunction should receive `Result<Return>` in the callback rather than `Return`:
> 
> ```rust
> #[napi]
> pub fn tsfn_call_with_callback(tsfn: ThreadsafeFunction<(), String>) -> napi::Result<()> {
>   tsfn.call_with_return_value(
>     Ok(()),
>     ThreadsafeFunctionCallMode::NonBlocking,
>     |value: Result<String>| {
>       let value = value.expect("Failed to retrieve value from JS");
>       println!("{}", value);
>       assert_eq!(value, "ReturnFromJavaScriptRawCallback".to_owned());
>       Ok(())
>     },
>   );
>   Ok(())
> }
> ```
> 
> Is this what you want?

Yes if it's also the same to strategy `Fatal`. Rspack would leverage the `Result<Return>` and try to extract the error stack from JS based on the `maybe_raw` from `JsError`. 
Ref: https://github.com/web-infra-dev/rspack/blob/b4028a0265d60a51018777459bf79b3f0ecb19a4/crates/rspack_napi/src/threadsafe_function.rs#L75-L83

**Pull request merged**
