### PR TITLE
feat(napi): impl Clone and Drop for ThreadSafeFunction, return Status  from ThreadSafeFunction::call

### PR DESCRIPTION
**Pull request by Brooooooklyn**
/cc @adumbidiot 

Close https://github.com/napi-rs/napi-rs/issues/277
Close https://github.com/napi-rs/napi-rs/issues/272

### CODE REVIEW

**Comment by adumbidiot** [comment]
Most of those `debug_assert!`s need to be `asserts`. Otherwise, compiling in release mode will silently use invalid values. Also, calling abort on one function will invalid all of them by sending an `napi_closing` error to the call function, which we need to intercept and track. After receiving this error, the function may be deallocated and should not be used. We should use that `aborted` flag to signal whether `raw_tsfn` is safe to use.

**Comment by adumbidiot** [comment]
I don't think a global atomic bool is necessary here? All we would need to do is make each tsfn clone have an aborted bool, and update it if call returns `napi_closing`. Otherwise, an abort to one function will abort all of them, even unrelated, un-aborted tsfns.

**Comment by Brooooooklyn** [comment]
> I don't think a global atomic bool is necessary here? All we would need to do is make each tsfn clone have an aborted bool, and update it if call returns napi_closing

I wrote a simple test case to test this case:

image

The print status is `Closing`. Which means **close cloned tsfn** will also close all `tsfn` shared the `napi_threadsafe_function`.

**Comment by adumbidiot** [comment]
I was concerned about something like:
```rust
let tsfn1 = ...
let tsfn2 = ...

tsfn1.abort()?;
let status = tsfn.call(Ok(vec![1, 2]), ThreadsafeFunctionCallMode::Blocking);
println!("{:#?}", status); // This should not be aborted since tsfn1 and tsfn2 are two different functions (not clones).
```

**Comment by Brooooooklyn** [comment]
I think `Arc<AtomicBool>` is suitable for this case

**Comment by adumbidiot** [comment]
I'm pretty sure you would still need a guard. Something like:
```rust
let tsfn = ...
let tsfn_clone = tsfn.try_clone().unwrap();

tsfn_clone.abort().unwrap();

// Not Safe
tsfn.call(Ok(vec![1, 2]), ThreadsafeFunctionCallMode::Blocking);
```

Also, calling abort and continuing to use other api functions is unsafe.

```rust
let tsfn = ...
tsfn.abort().unwrap();

// Not Safe
tsfn.call(Ok(vec![1, 2]), ThreadsafeFunctionCallMode::Blocking);
```

**Comment by Brooooooklyn** [comment]
> I'm pretty sure you would still need a guard. For example, the following isn't safe:

Yes, I will add guard in `call` method.

> Also, calling abort and continuing to use other api functions is unsafe:

hmmm, this situation will never happen because `abort` take the ownership and can not call `call` method then.

**Comment by adumbidiot** [comment]
Oops missed that function signature. abort seems fine then.

I think you would need to use guards for all  tsfn functions. For example:
```
let tsfn = ...
let tsfn_clone = tsfn.clone();

tsfn_clone.abort().unwrap();

// Safe due to guard
tsfn.call(Ok(vec![1, 2]), ThreadsafeFunctionCallMode::Blocking);

// Not Safe, lacks guard. 
// Furthermore, raw_tsfn is definitely deallocated here as every function has called abort and/or received napi_closing from call
tsfn.try_clone().unwrap();
```

**Comment by Brooooooklyn** [comment]
`try_clone` already guarded. I think`refer/unref` don't need to be guarded because they can only be called within main thread, and return `Error` if something was wrong.

**Comment by adumbidiot** [comment]
The problem isn't which thread they can be called from, but whether the tsfn still exists.

From the docs:
> Upon receiving a return value of napi_closing from napi_call_threadsafe_function() a thread must not use the thread-safe function anymore because it is no longer guaranteed to be allocated

So we must guard all usages of raw_tsfn

**Pull request merged**
