### PR TITLE
Add windows gnu target

### LINKED ISSUE #1893: Crash in msys2 environment
It may happen because `rollup` and not `napi-rs`, but I'll open this issue just for any case.

When running rollup inside `msys2` environment in `ucrt64` terminal I get the following error:
```console
$ npx rollup --version
thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\napi-sys-2.3.0\src\functions.rs:7:3:
Must load N-API bindings
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
https://github.com/rollup/rollup/issues/5333
https://github.com/rustwasm/wasm-pack/issues/1359

### LINKED ISSUE #2001: Support `x86_64-pc-windows-gnu` toolchain ?
I uses msys2 rust, which build target is `x86_64-pc-windows-gnu` （output file name is `index.win32-x64-gnu.node`）. I hope this toolchain could be supported. Currently only `win32-x64-msvc` supported.

```
? Choose targets you want to support (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
 ( ) armv7-unknown-linux-gnueabihf
 (*) x86_64-apple-darwin
 (*) x86_64-pc-windows-msvc
>(*) x86_64-unknown-linux-gnu
 ( ) x86_64-unknown-linux-musl
 ( ) x86_64-unknown-freebsd
 ( ) i686-pc-windows-msvc
```

And the generated `index.js` only judgements `x86_64-pc-windows-msvc`:

```js
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-x64-msvc.node')
          } else {
            nativeBinding = require('index-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
```

### PR DESCRIPTION
**Pull request by Kreijstal**
Good day, 

I am not well acquainted with this project or rust or node api, but there has been this bug that has been bugging me for a while, when using napi-rs, I put msvc target on its own category, since it is different from clang or gcc, and added static linking for windows, I added a build.rs script for napi, so that you can `cargo test` on the repository. Additionally I added dynamical symbol loading for gnu targets as well, so you can either choose to static or dynamic load, since I do not have msvc, I can not test how this works for msvc, but since I did not change its path, it should work as it has worked before. I noticed some people have the same issue and someone even came with a patch!/Workaround!

Fixes #2001 
Fixes #1893

related https://github.com/napi-rs/napi-rs/issues/1480#issuecomment-1727034104 (patch came from this thread)

Please review

### CODE REVIEW

**Comment by Kreijstal** [comment]
and the dependencies might have to be updated as well, because this is self hosting
```
➤ YN0009: │ nx@npm:18.0.6 [fa6ee] couldn't be built successfully (exit code 3765269347, logs can be found here: C:
\msys2\2023-01-27\tmp\xfs-2c598937\build.log)
```` 

```
# This file contains the result of Yarn building a package (nx@virtual:fa6eeaa7c9f4e1db0f350601993a6029e8bb72c06889f8cfb84b0d52baf2222c364ee2e33fef459cbbe21959a676ab0d1a5b88ec4e42655dd590db72a28ac7fe#npm:18.0.6)
# Script name: postinstall

thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\napi-sys-2.2.3\src\functions.rs:7:3:
Must load N-API bindings
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kreijstal** [comment]
Ah, I see the failing tests, Ill work on that

**Comment by Kreijstal** [comment]
I understand, msvc is not a configuration but target_env="msvc" is.

**Comment by Brooooooklyn** [comment]
@Kreijstal can you add a Windows gnu CI to test the platform?

**Comment by Kreijstal** [comment]
> @Kreijstal can you add a Windows gnu CI to test the platform?

I added test that tell you that it compiles at least with rust, in the msys2 platform however the tests will fail since they can't install rollup, for the reason that this pull request is precisely trying to fix.

**Pull request merged**
