### PR TITLE
refactor(cli): refactor js-binding to support easier bundling.

### PR DESCRIPTION
**Pull request by everett1992**
https://github.com/napi-rs/napi-rs/issues/1948

This PR addresses two issues I had with using the JavaScript generated by @napi-rs/cli with a bundler.
1. The existsSync check before require breaks if the bundler renames the .node file
2. platform, arch cannot be defined at build time.

With this change `esbuild` can bundle napi-rs libraries with just `--loader:.node=copy` and webpack can bundle with node-loader.
Before I was able to use esbuild by disabling asset hashing, but I wasn't able to get webpack working.

Additionally you can define process.arch and process.platform at build time and requires to unused platforms/arch's will be eliminated and not included in the bundle.

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
NAPI-RS had a similar implementation before; but it breaks another tools like `ncc` on Vercel: https://github.com/napi-rs/node-rs/issues/316

**Comment by everett1992** [comment]
Do you have a link to that similar implementation?

I tested this PR with @vercel/ncc, esbuild, and webpack with both grouped and separated package binaries.
This implementation seems more likely to work across all bundlers because it doesn't use any `require.resolve` or file system checks. It's the same pattern you're currently using for separated package binaries, but I use it for both separated and grouped, and skip the file exists check. 

```typescript
 function requireNative() {
  if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./rust-cloudauth-core.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@amzn/rust-cloudauth-core-android-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

```

**Comment by Brooooooklyn** [comment]
> Do you have a link to that similar implementation?

https://github.com/napi-rs/node-rs/blob/main/packages/helper/src/loader.ts

For loading logic like this:
```js
function requireNative() {
  if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./rust-cloudauth-core.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('@amzn/rust-cloudauth-core-android-arm64')
      } catch (e) {
        loadErrors.push(e)
      }
```

I'm worried that such logic is too dynamic, some packing tools that are not implemented finely may not be able to analyze the actual path/package required.

**Comment by everett1992** [comment]
Which part are you worried about?

I could remove the requireNative function.
try require catch is what you're currently doing. I changed to an array of
errors, but could revert.
I think this is less dynamic because it removes a runtime fs exists check.

**Pull request merged**
