### PR TITLE
feat(cli): detect Cargo `--profile` argument

### PR DESCRIPTION
**Pull request by lucasfernog**
I actually need this feature on the v2 CLI, do you think you could backport and publish it? I used patch-package [on the Tauri PR](https://github.com/tauri-apps/tauri/pull/6861) but it's.. ugly :smile: 

I wanted to push to v2 instead but I couldn't find how you are handling it, I guess you're doing it manually?

### CODE REVIEW

**Comment by lucasfernog** [comment]
Maybe at this point it's easier to add a `profile` argument instead of parsing `cargoOptions`? Let me know.

**Comment by Brooooooklyn** [comment]
> Do you think you could backport and publish it? 

Yes sure, I'll backport it after this is merged

**Comment by Brooooooklyn** [comment]
@lucasfernog backport to https://github.com/napi-rs/napi-rs/releases/tag/%40napi-rs%2Fcli%402.16.0

**Comment by lucasfernog** [comment]
@Brooooooklyn the `this.profile ?? this.isRelease ? 'release' : 'debug'` logic is wrong. When `profile` is set you actually need to use that instead of `release | debug`. So the actual code would be something like:

```javascript
const targetDir = join(
    this.targetTripleDir,
    this.profile || (this.isRelease ? 'release' : 'debug'),
)
```

**Comment by Brooooooklyn** [comment]
@lucasfernog fixed again

**Pull request merged**
