### PR TITLE
chore: cargo build --watch

### PR DESCRIPTION
**Pull request by stone-jin**
#407

usage: 
```
$ cargo build --watch
```

cargo build --help echo:
```
 --watch       watch and rebuild napi package
```

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
@stone-jin Thank you for contributing. I'll merge it after 2.0.1 is released. Because it's a big feature and I want to do some more works top on it.

**Comment by stone-jin** [comment]
got it. @Brooooooklyn

**Comment by forehalo** [comment]
Maybe we should rewrite the cli tool in rust as well, so it can work with [cargo-watch](https://crates.io/crates/cargo-watch) out of box.
And also the current cli tool written in node smells bad because of the progressing of migrating to esm modules. I can't believe we need to bundle node program. 😞
IMO, it's good time to redesign it.

**Comment by Brooooooklyn** [comment]
Yes, we should rewrite the cli in `Rust` also because of
- https://github.com/napi-rs/napi-rs/issues/981

**Comment by stone-jin** [comment]
🙋‍♂️ support it

**Comment by forehalo** [comment]
well, I think it would be fine to close this PR because of #1074, you may want to contribute to that PR if you might hurry to use the `watch` ability

**Pull request closed without merging**
